### PR TITLE
Add Windows taskbar integration.

### PR DESCRIPTION
**Pull request by shemanaev**
Some nice touches like progress indication and pause/resume button. 

изображение

### CODE REVIEW

**Comment by iwalton3** [comment]
I re-worked this a bit so that the web client doesn't have to worry about it and added prev/next buttons:
image

You can download a test build if you want to play with it: https://github.com/jellyfin/jellyfin-media-player/suites/2570654482/artifacts/56031875

**Comment by shemanaev** [comment]
Nice. For some reason i was convinced that jellyfin-web needs to be patched for prev/next.

**Comment by iwalton3** [comment]
What I did is I bound the button events to the input manager instead. And subscribed directly to the MPV player for progress info.

https://github.com/jellyfin/jellyfin-media-player/blob/master/src/taskbar/TaskbarComponentWin.cpp

**Comment by shemanaev** [comment]
Yeah, checked it out already. Wasn't familiar with input manager codebase though.

**Comment by iwalton3** [comment]
I only recently added support for it and it is kind of confusing. Plus I had to edit both the player and input components to make everything work.

**Pull request merged**
