### PR TITLE
Properly enable QWebEngine GPU acceleration

### PR DESCRIPTION
**Pull request by TheFeelTrain**
Mentioned here: https://github.com/jellyfin/jellyfin-media-player/issues/10

I noticed the interface was lagging a lot when using a theme that has blurred backdrops (disabling the backdrops made it smooth again so I know that was the culprit). I knew it was because of a lack of hardware acceleration, and I stumbled across this issue and realized it was never actually enabled.

The difference in performance is night and day for me when compiled with this flag enabled.

### CODE REVIEW

**Comment by iwalton3** [comment]
Could you make the `disable-gpu` flag work with this?

**Comment by TheFeelTrain** [comment]
I'm not sure what you mean, could you elaborate? I'm not sure how you could have GPU rasterization with the GPU disabled...

**Comment by iwalton3** [comment]
I have a `--disable-gpu` command flag that should shut off GPU acceleration if it bugs out on someone's computer. Now if that gpu rasterization flag is automatically disabled with `--disable-gpu` that would be helpful.

**Comment by TheFeelTrain** [comment]
`--disable-gpu` does seem to still disable the GPU. Performance gets tanked when launching with it. We could also add move `--enable-gpu-rasterization` to the options instead of enabling it by default if that makes more sense to do.

**Pull request merged**
