### PR TITLE
fix: skipintro plugin client freeze

### LINKED ISSUE #405: Small client freeze when "skip intro" button is used
**Describe the bug**
When using the "Skip Intro" functionality as part of said plugin, my client freezes for around 10-20 seconds. I've had this happen consistently over multiple series. This didn't happen before 1.9.0.

**To Reproduce**
1. Have "Skip Intro" enabled (of course on the server as well)
2. Start watching an episode until the button shows up
3. Click the button, and watch the client freeze up for a bit

**Expected behavior**
For the client to skip to the end of the intro without any freezes.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 1.9.0
 - Installation Method: Official build, Windows installer.

**Additional context**
Closing the client while frozen gets audio playing for a couple seconds (but then closes the client, like it should).

### PR DESCRIPTION
**Pull request by ThePesta**
Fixes #405

The skip intro button click handler is triggered multiples times after pressing the skip intro button, causing a client freeze.

Tested on Win11.

### CODE REVIEW

**Review by iwalton3 — APPROVED** [review]

**Comment by kmaid** [comment]
Any idea when this will be in a release? The artifact from this build expired and the latest build macos came up as broken on my machine

**Comment by viggy96** [comment]
Can we do another point release to put out this fix? Using the flatpak version of JMP currently.

**Comment by viggy96** [comment]
Any reason we can't do another quick release so users have this fix?

**Comment by kmaid** [comment]
Sorry to tag you directly but think you could take a look @iwalton3

**Pull request merged**
